"""Initial_schema

Revision ID: 05b279f3899e
Revises: 
Create Date: 2026-01-22 11:09:01.400096

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '05b279f3899e'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_log',
    sa.Column('entity_type', sa.String(length=50), nullable=True),
    sa.Column('entity_id', sa.UUID(), nullable=True),
    sa.Column('action', sa.String(length=50), nullable=True),
    sa.Column('actor', sa.String(length=255), nullable=True),
    sa.Column('details', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('campaigns',
    sa.Column('external_id', sa.String(length=50), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('target_industry', sa.String(length=100), nullable=True),
    sa.Column('target_persona', sa.String(length=100), nullable=True),
    sa.Column('target_region', sa.String(length=50), nullable=True),
    sa.Column('sequence_touches', sa.Integer(), nullable=False),
    sa.Column('touch_delays', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('template_type', sa.String(length=50), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('external_id')
    )
    op.create_table('domain_health',
    sa.Column('domain', sa.String(length=255), nullable=False),
    sa.Column('warmup_started_at', sa.DateTime(), nullable=True),
    sa.Column('warmup_completed', sa.Boolean(), nullable=False),
    sa.Column('daily_limit', sa.Integer(), nullable=False),
    sa.Column('bounce_rate_7d', sa.Numeric(precision=5, scale=4), nullable=True),
    sa.Column('spam_rate_7d', sa.Numeric(precision=5, scale=4), nullable=True),
    sa.Column('spf_valid', sa.Boolean(), nullable=True),
    sa.Column('dkim_valid', sa.Boolean(), nullable=True),
    sa.Column('dmarc_valid', sa.Boolean(), nullable=True),
    sa.Column('last_dns_check_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('domain')
    )
    op.create_table('leads',
    sa.Column('external_id', sa.String(length=50), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('first_name', sa.String(length=100), nullable=True),
    sa.Column('last_name', sa.String(length=100), nullable=True),
    sa.Column('company_name', sa.String(length=255), nullable=False),
    sa.Column('company_domain', sa.String(length=255), nullable=False),
    sa.Column('linkedin_url', sa.String(length=500), nullable=True),
    sa.Column('mobile', sa.String(length=50), nullable=True),
    sa.Column('region', sa.String(length=50), nullable=True),
    sa.Column('industry', sa.String(length=100), nullable=True),
    sa.Column('persona', sa.String(length=100), nullable=True),
    sa.Column('fit_score', sa.Numeric(precision=3, scale=2), nullable=True),
    sa.Column('readiness_score', sa.Numeric(precision=3, scale=2), nullable=True),
    sa.Column('intent_score', sa.Numeric(precision=3, scale=2), nullable=True),
    sa.Column('composite_score', sa.Numeric(precision=3, scale=2), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('risk_level', sa.String(length=20), nullable=True),
    sa.Column('risk_reason', sa.Text(), nullable=True),
    sa.Column('personalization_mode', sa.String(length=20), nullable=False),
    sa.Column('researched_at', sa.DateTime(), nullable=True),
    sa.Column('last_contacted_at', sa.DateTime(), nullable=True),
    sa.Column('unsubscribed_at', sa.DateTime(), nullable=True),
    sa.Column('consent_given_at', sa.DateTime(), nullable=True),
    sa.Column('data_retention_until', sa.DateTime(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('external_id')
    )
    op.create_index('idx_leads_composite_score', 'leads', [sa.literal_column('composite_score DESC')], unique=False)
    op.create_index('idx_leads_domain', 'leads', ['company_domain'], unique=False)
    op.create_index('idx_leads_status', 'leads', ['status'], unique=False)
    op.create_table('suppression_list',
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('domain', sa.String(length=255), nullable=True),
    sa.Column('reason', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_index('idx_suppression_domain', 'suppression_list', ['domain'], unique=False)
    op.create_index('idx_suppression_email', 'suppression_list', ['email'], unique=False)
    op.create_table('templates',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('type', sa.String(length=50), nullable=False),
    sa.Column('touch_number', sa.Integer(), nullable=False),
    sa.Column('subject_template', sa.Text(), nullable=False),
    sa.Column('body_template', sa.Text(), nullable=False),
    sa.Column('required_variables', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('times_used', sa.Integer(), nullable=False),
    sa.Column('avg_open_rate', sa.Numeric(precision=5, scale=4), nullable=True),
    sa.Column('avg_reply_rate', sa.Numeric(precision=5, scale=4), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('campaign_leads',
    sa.Column('campaign_id', sa.UUID(), nullable=False),
    sa.Column('lead_id', sa.UUID(), nullable=False),
    sa.Column('current_touch', sa.Integer(), nullable=False),
    sa.Column('next_touch_at', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('stopped_reason', sa.String(length=100), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaigns.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['lead_id'], ['leads.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_campaign_leads_next_touch', 'campaign_leads', ['next_touch_at'], unique=False)
    op.create_index('idx_campaign_leads_unique', 'campaign_leads', ['campaign_id', 'lead_id'], unique=True)
    op.create_table('drafts',
    sa.Column('lead_id', sa.UUID(), nullable=False),
    sa.Column('campaign_id', sa.UUID(), nullable=True),
    sa.Column('template_id', sa.UUID(), nullable=True),
    sa.Column('touch_number', sa.Integer(), nullable=False),
    sa.Column('subject_options', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('selected_subject', sa.Text(), nullable=True),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('strategy', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('evidence', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('personalization_mode', sa.String(length=20), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('approved_by', sa.String(length=255), nullable=True),
    sa.Column('approved_at', sa.DateTime(), nullable=True),
    sa.Column('rejection_reason', sa.Text(), nullable=True),
    sa.Column('scheduled_send_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaigns.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['lead_id'], ['leads.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['template_id'], ['templates.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_drafts_scheduled', 'drafts', ['scheduled_send_at'], unique=False)
    op.create_index('idx_drafts_status', 'drafts', ['status'], unique=False)
    op.create_table('lead_intelligence',
    sa.Column('lead_id', sa.UUID(), nullable=False),
    sa.Column('your_services', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('your_proof_points', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('your_positioning', sa.Text(), nullable=True),
    sa.Column('lead_offerings', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('lead_pain_indicators', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('lead_buying_signals', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('lead_tech_stack', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('linkedin_role', sa.String(length=500), nullable=True),
    sa.Column('linkedin_seniority', sa.String(length=50), nullable=True),
    sa.Column('linkedin_topics_30d', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('linkedin_job_change_days', sa.Integer(), nullable=True),
    sa.Column('linkedin_likely_initiatives', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('linkedin_raw_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('linkedin_decision_power', sa.Boolean(), nullable=True),
    sa.Column('linkedin_budget_authority', sa.String(length=50), nullable=True),
    sa.Column('linkedin_lead_score', sa.Integer(), nullable=True),
    sa.Column('cold_email_hooks', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('opening_line', sa.Text(), nullable=True),
    sa.Column('triggers', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('pain_hypotheses', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('best_angle', sa.String(length=100), nullable=True),
    sa.Column('researched_at', sa.DateTime(), nullable=False),
    sa.Column('is_stale', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['lead_id'], ['leads.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('lead_id')
    )
    op.create_table('email_events',
    sa.Column('draft_id', sa.UUID(), nullable=True),
    sa.Column('lead_id', sa.UUID(), nullable=False),
    sa.Column('campaign_id', sa.UUID(), nullable=True),
    sa.Column('event_type', sa.String(length=50), nullable=False),
    sa.Column('touch_number', sa.Integer(), nullable=True),
    sa.Column('sendgrid_message_id', sa.String(length=255), nullable=True),
    sa.Column('reply_sentiment', sa.String(length=20), nullable=True),
    sa.Column('reply_intent', sa.String(length=50), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaigns.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['draft_id'], ['drafts.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['lead_id'], ['leads.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_events_campaign', 'email_events', ['campaign_id'], unique=False)
    op.create_index('idx_events_lead', 'email_events', ['lead_id'], unique=False)
    op.create_index('idx_events_type', 'email_events', ['event_type'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_events_type', table_name='email_events')
    op.drop_index('idx_events_lead', table_name='email_events')
    op.drop_index('idx_events_campaign', table_name='email_events')
    op.drop_table('email_events')
    op.drop_table('lead_intelligence')
    op.drop_index('idx_drafts_status', table_name='drafts')
    op.drop_index('idx_drafts_scheduled', table_name='drafts')
    op.drop_table('drafts')
    op.drop_index('idx_campaign_leads_unique', table_name='campaign_leads')
    op.drop_index('idx_campaign_leads_next_touch', table_name='campaign_leads')
    op.drop_table('campaign_leads')
    op.drop_table('templates')
    op.drop_index('idx_suppression_email', table_name='suppression_list')
    op.drop_index('idx_suppression_domain', table_name='suppression_list')
    op.drop_table('suppression_list')
    op.drop_index('idx_leads_status', table_name='leads')
    op.drop_index('idx_leads_domain', table_name='leads')
    op.drop_index('idx_leads_composite_score', table_name='leads')
    op.drop_table('leads')
    op.drop_table('domain_health')
    op.drop_table('campaigns')
    op.drop_table('audit_log')
    # ### end Alembic commands ###
